# Generated by Django 3.0.5 on 2020-07-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20200723_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='author',
            new_name='user',
        ),
    ]
